service: taskbackendapi
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  lambdaHashingVersion: 20201221
  region: eu-west-2
  profile: serverless
package:
  artifact: target/tasks-api-java-dev.jar

functions:
  get-tasks-java-api:
    handler: com.impact.GetTasksHandler
    events:
      - http:
          path: /users/{userId}/tasks
          method: get